
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ARRAY ASSIGN BEGIN CASE COLON COMMA CONST DIV DIV DO DOT DOTDOT DOWNTO ELSE END EQUAL FOR FUNCTION GE GOTO GT ID IF KEY_WORD_NOT LB LE LP LT MINUS MOD MOD MUL NUMBER OF OPERATOR_NOT OR PACKED PLUS PROCEDURE PROGRAM RB RECORD REPEAT RP SEMI THEN TO TYPE UNEQUAL UNTIL VAR WHILEfactor : NUMBER'
    
_lr_action_items = {'NUMBER':([0,],[1,]),'$end':([1,2,],[-1,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'factor':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> factor","S'",1,None,None,None),
  ('factor -> NUMBER','factor',1,'p_factor_num','myyacc.py',13),
]
