lexermake: src/lexer.py
	cp src/lex.py bin/lex.py
	cp src/lexer.py bin/lexer
	cp src/reserved_tokens.py bin/reserved_tokens.py
	cp src/tokens.py bin/tokens.py
	chmod u+x bin/lexer

clean: 
	rm -rf bin
	mkdir bin
