codemake: src/main.py
	cp src/SymTable.py bin/SymTable
	cp src/main.py bin/codegen
	cp src/codegen.py bin/codegen.py
	cp src/varAllocateRegister.py bin/varAllocateRegister.py
	cp src/ThreeAddrCode.py bin/ThreeAddrCode.py
	chmod u+x bin/codegen

clean: 
	rm -rf bin
	mkdir bin
