lexermake: src/lexer.py src/parser.py
	cp src/SymTable.py bin/SymTable.py
	cp src/ThreeAddrCode.py bin/ThreeAddrCode.py
	cp src/lexer.py bin/lexer.py
	cp src/reserved_tokens.py bin/reserved_tokens.py
	cp src/tokens.py bin/tokens.py
	cp src/parser.py bin/irgen

clean: 
	rm -rf bin
	mkdir bin
