lexermake: src/lexer.py src/parser.py
	cp src/lexer.py bin/lexer.py
	cp src/reserved_tokens.py bin/reserved_tokens.py
	cp src/tokens.py bin/tokens.py
	cp src/parser.py bin/parser
	chmod u+x bin/parser

clean: 
	rm -rf bin
	mkdir bin
